---
#
# Playbook installs DataStax Enterprise on Centos7 VM
#
# run this playbook with the following command:
#
#     ansible-playbook -i "127.0.0.1:2222," dse.yml --extra-vars "dsa_email=your@email.com" --extra-vars "dsa_key=downloadkey"
#
- name: Installing DataStax Enterprise from offical YUM repo
  hosts: all
  user: centos
  become: yes
  tasks:

  - name: Enable EPEL repo
    yum:
      name: epel-release
      state: installed

  - name: Install utilities
    yum:
      name:
        - jq
        - htop
        - telnet
        - tmux
        - wget
        - unzip
      state: installed

  - name: Install DataStax Enterprise prerequisites
    yum:
      name:
        - libaio
        - java-1.8.0-openjdk-headless
      state: installed

  - name: Add official DataStax YUM repository
    yum_repository:
      name: datastax
      description: YUM Repo for DataStax Enterprise
      file: datastax
      baseurl: "https://{{ dsa_email|urlencode() }}:{{ dsa_key|urlencode() }}@rpm.datastax.com/enterprise/"
      gpgcheck: yes

  - rpm_key:
      state: present
      key: https://rpm.datastax.com/rpm/repo_key

  - name: install DataStax Enterprise packages
    yum:
      name: 
        - dse-full
        - dse-demos
      state: installed

  - name: Enable features of DataStax Enterprise
    lineinfile:
      path: /etc/default/dse
      regexp: "{{ item.regexp }}"
      line: '\1=1'
      backrefs: yes
    with_items:
      - { regexp: '^(SPARK_ENABLED)=0' }
      - { regexp: '^(GRAPH_ENABLED)=0' }

  # user is created by dse package but home directory
  # does not exist. we'll create it
  - name: Creates home directory for cassandra
    user:
      name: cassandra
      home: /home/cassandra
      move_home: yes
      state: present
      skeleton: yes

  - name: Copy helper scripts
    copy:
      src: "{{ item }}"
      dest: "/home/cassandra/{{ item }}"
      owner: cassandra
      group: cassandra
      mode: 0755
    with_items:
      - setup_dir.sh
      - setup_sdkman.sh

