#
# use this to launch a vagrant centos7 box to test the playbook
#

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provision "shell",
    inline: "useradd -g vagrant centos"
end
