---
#
# run this playbook with the following command:
#
#     ansible-playbook -i "m.t.co," influxdb.yml --extra-vars "fqdn=d.vino9.net"
# 
- name: Installing software packages for monitoring host
  hosts: all
  user: ec2-user
  tasks:

  - name: install influxdb
    yum:
      name: https://dl.influxdata.com/influxdb/releases/influxdb-1.7.2.x86_64.rpm
      state: installed
      disable_gpg_check: yes
    become: yes

  - name: start influxdb
    systemd:
      state: started
      name: influxdb
    become: yes
      
  - name: install chronograf
    yum:
      name: https://dl.influxdata.com/chronograf/releases/chronograf-1.7.5.x86_64.rpm
      state: installed
      disable_gpg_check: yes
    become: yes

  - name: configure chronograf
    copy:
      dest: /etc/default/chronograf
      mode: 0644
      content: |
        CHRONOGRAF_OPTS="--basepath /chronograf"
    become: yes
    notify:
      - restart chronograf

  - name: start chronograf
    systemd:
      state: started
      name: chronograf
    become: yes
      
  - name: install grafana
    yum:
      name: https://dl.grafana.com/oss/release/grafana-5.4.2-1.x86_64.rpm
      state: installed
      disable_gpg_check: yes
    become: yes

  - name: configure grafana
    tasks:
      - name: update domain setting
        lineinfile:
          path: /etc/grafana/grafana.ini
          regexp: '^domain ='
          insertafter: "^;domain = localhost"
          line: "domain = {{ fqdn }}"
      - name: update root_url setting
        lineinfile:
          path: /etc/grafana/grafana.ini
          regexp: '^root_url ='
          insertafter: "^;root_url = http://localhost"
          line: "root_url =  https://{{ fqdn }}/grafana"
      become: yes
      notify:
        - restart grafana

  - name: start grafana
    systemd:
      state: started
      name: grafana-server
    become: yes

  - handlers:
    - name: restart chronograf
      systemd:
        name: chronograf
        state: restarted

    - name: restart grafana
      systemd:
        name: grafana-server
        state: restarted
