---
#
# run this playbook with the following command:
#
#     ansible-playbook -i "m.t.co," infra.yml --extra-vars "fqdn=d.vino9.net"
# 
- name: Installing software packages for monitoring host
  hosts: all
  user: ec2-user
  tasks:

  - name: Install Influx DB
    yum:
      name: https://dl.influxdata.com/influxdb/releases/influxdb-1.7.2.x86_64.rpm
      state: installed
      disable_gpg_check: yes
    become: yes

  - name: Start InfluxDB
    systemd:
      state: started
      name: influxdb
    become: yes
      
  - name: Install Chronograf
    yum:
      name: https://dl.influxdata.com/chronograf/releases/chronograf-1.7.5.x86_64.rpm
      state: installed
      disable_gpg_check: yes
    become: yes

  - name: Change Chronograf basepath 
    copy:
      dest: /etc/default/chronograf
      mode: 0644
      content: |
        CHRONOGRAF_OPTS="--basepath /chronograf"
    become: yes

  - name: Start Chronograf
    systemd:
      state: started
      name: chronograf
    become: yes
      
  - name: Install Grafana
    yum:
      name: https://dl.grafana.com/oss/release/grafana-5.4.2-1.x86_64.rpm
      state: installed
      disable_gpg_check: yes
    become: yes

  - name: Configure Grafana for reverse proxy 1
    lineinfile:
      path: /etc/grafana/grafana.ini
      regexp: '^domain ='
      insertafter: "^;domain = localhost"
      line: "domain = {{ fqdn }}"
    become: yes

  - name: Configure Grafana for reverse proxy 2
    lineinfile:
      path: /etc/grafana/grafana.ini
      regexp: '^root_url ='
      insertafter: "^;root_url = http://localhost"
      line: "root_url =  https://{{ fqdn }}/grafana"
    become: yes

  - name: Start Grafana
    systemd:
      state: started
      name: grafana-server
    become: yes
      
