---

- name: Installing software packages for monitoring host
  hosts: all
  user: ec2-user
  tasks:

  - name: Install Influx DB
    yum:
      name: https://dl.influxdata.com/influxdb/releases/influxdb-1.7.2.x86_64.rpm
      state: installed
      disable_gpg_check: yes
    become: yes

  - name: Install Chronograf
    yum:
      name: https://dl.influxdata.com/chronograf/releases/chronograf-1.7.5.x86_64.rpm
      state: installed
      disable_gpg_check: yes
    become: yes

  - name: Install Grafana
    yum:
      name: https://dl.grafana.com/oss/release/grafana-5.4.2-1.x86_64.rpm
      state: installed
      disable_gpg_check: yes
    become: yes
