all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: ec2-user
    ansible_become: true
    security_mode: plain_text
#    security_mode: sasl_ssl
preflight:
  hosts:
    zk1.t.co:
    b1.t.co:
    b2.t.co:
    b3.t.co:
    conn.t.co:
    kt.t.co:
ssl_CA:
  hosts:
zookeeper:
  hosts:
    zk1.t.co:
broker:
  hosts:
    b1.t.co:
      kafka:
        broker:
          id: 1
    b2.t.co:
      kafka:
        broker:
          id: 2
    b3.t.co:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    kt.t.co:
control-center:
  hosts:
#    kt.t.co:
#      confluent:
#        control:
#          center:
#            config:
#              confluent.controlcenter.connect.cluster: 
connect-distributed:
  hosts:
    conn.t.co:
kafka-rest:
  hosts:
ksql:
  hosts:
    conn.t.co:
tools:
  hosts:
    kt.t.co:
